name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            .chatvenv\Lib\site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv .chatvenv
          .chatvenv\Scripts\activate
          pip install -r requirements.txt

      - name: Run tests
        run: python --version

      - name: Run pytest
        run: |
          .chatvenv\Scripts\activate
          pytest --maxfail=1 --disable-warnings -q
